name: Auto-Update Anime 24/7 M3U Playlist

on:
  schedule:
    - cron: "0 6 * * *"  # daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update-anime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Generator Script
        run: python anime_247_generator.py

      - name: Commit Updated M3U
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/anime_247.m3u
          git commit -m "🔄 Auto-update: anime_247.m3u" || echo "No changes"
          git push
